### ISSUE TITLE
Fix trivial broken test

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/kiri#1]
Fix the following test, find it by searching for `Issue 1`:

```
    if False:
        # Issue 1
        b = Board()
        assert b.n_cols == 3, "A board has four columns"
```

Currently, the test is:
 * disabled, as an `if False` will never be true
 * commented by `# Issue 1`, so it can be found
 * incorrect, as the assertion `b.n_cols == 3` contains a typo

Fix it to:

```
    if True:
        b = Board()
        assert b.n_cols == 4, "A board has four columns"
```

Then, the test is:
 * enabled, as an `if True` will always be true
 * has no redundant commented `# Issue 1`
 * correct, as the assertion `b.n_cols == 4` is correct

Tip: to run only the tests, do from the command line: `python main.py --test`

After fixing the test, push. After a successful build, merge to develop.

**Comment by Kirsten29** [comment]
Done, fixed #1
