### ISSUE TITLE
A board is not empty after a peg is placed

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/kiri#11]
Depends on:

 * [x] #10 

A fresh board is empty, until one peg is placed:

```
    if False:
        # Issue 11
        b = Board()
        b.print_me()
        b.set_color(0, 0, "red")
        b.print_me()
        # assert !b.is_empty(), "A board is not empty after a peg is placed"
```

 * Activate the test
 * Remove the comment
 * Uncomment the `assert` statement
 * Instead of `!b.is_empty()` maybe on needs `not b.is_empty()`
 * `b.print_me()` shows the content of the board in text, remove it after this test has passed
 * Make the test pass in any way. You can even be sneaky and add a variable to keep track if a move is done. Also, do not check if the color is valid.
 * Add, commit, push

**Comment by Kirsten29** [comment]
Truly fixed #11 this time
