### ISSUE TITLE
Encode the number of rows a board has

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/kiri#2]
Depends on:

 * [x] #1 

There is a test like this, find it by searching for `Issue 2`:

```
    if False:
        # Issue 2
        b = Board()
        assert b.n_rows == -1, "A board has ? rows"
```

Currently, the test is:
 * disabled, as an `if False` will never be true
 * commented by `# Issue 2`, so it can be found
 * incorrect, as the assertion `b.n_rows == -1` is false: a board has a positive number of rows. Also the comment is vague with the question mark

Fix it to:

```
    if True:
        b = Board()
        assert b.n_rows == [number], "A board has  [number] columns"
```

Then, the test is:
 * enabled, as an `if True` will always be true
 * has no redundant commented `# Issue 2`
 * correct, as the assertion is correct

Tip: to run only the tests, do from the command line: `python main.py --test`

After fixing the test, push. After a successful build, merge to develop.

**Comment by Kirsten29** [comment]
Done, corrected nr. of rows and #2.
