### ISSUE TITLE
A player has 6 peg colors

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/kiri#4]
A player has six peg colors. The code, however, is incorrect, a the following test will fail (if set to `if True:`)

```
    if False:
        # Issue 4
        assert get_n_player_peg_colors() == 6, "The player has 6 peg colors"
```

 * Activate the test
 * Remove the comment
 * Fix `get_n_player_peg_colors`
 * Add, commit, push

**Comment by Kirsten29** [comment]
Done, #4  and build passed.
