### ISSUE TITLE
There are 6 peg colors

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/kiri#5]
Depends on:

 * [ ] #4 

A player has six peg colors. The code, however, is incorrect, a the following test will fail (if set to `if True:`)

```
    if False:
        # Issue 5
        n_expected = get_n_player_peg_colors()
        n_actual = len(get_player_peg_colors())
        assert n_expected == n_actual, "There must be 6 peg colors"
```

 * Activate the test
 * Remove the comment
 * Fix `get_player_peg_colors`, which should return 6 colors. Which six colors are unimportant (this will be a new Issue)
 * Add, commit, push

**Comment by Kirsten29** [comment]
Done, fixed #5 and corrected error.
