### ISSUE TITLE
Draw a rectangle to resemble the board

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/kiri#7]
Currently, we have a `Board` class, of which we can get the number of rows and columns.

Draw a rectangle of the correct dimensions that fit in the window, e.g

 * 32 pixels times number of columns wide
 * 32 pixels times the number of rows high

The rectangle should have a fill color and a contour color, e.g. filled with light brown and a dark brown contour.

Where the board is drawn on the window (i.e. top-left, centered, someplace else) is irrelevant: this is a separate Issue. Feel free to move the 'MASTERMIND' title to a better spot :+1:

**Comment by Kirsten29** [comment]
Rectangle drawn, #7 fixed.
